#!/usr/bin/with-contenv sh

# Build the dump1090 command line based on piaware options
if [ -z "${BASESTATIONHOST}" ]; then
  sleep 3600  
else
  socat -d -d TCP-LISTEN:30003,fork TCP:${BASESTATIONHOST}:${BASESTATIONPORT}
fi

