#!/usr/bin/with-contenv sh

# Check to make sure the correct command line arguments have been set
EXITCODE=0
if [ -z "${USERNAME}" ]; then
  echo "ERROR: USERNAME environment variable not set"
  EXITCODE=1
fi
if [ -z "${PASSWORD}" ]; then
  echo "ERROR: PASSWORD environment variable not set"
  EXITCODE=1
fi
if [ $EXITCODE -ne 0 ]; then
  exit 1
fi

# Set up timezone
if [ -z "${TZ}" ]; then
  echo "WARNING: TZ environment variable not set"
else
  ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
fi

# Install operator photos
echo "Installing operator flags..."
cp -R /opt/VRS_Extras/bonesaviation/operator-logo-starter-pack/* /config/operatorflags
cp -R /opt/VRS_Extras/dedevillela/VRS-Operator-Flags/OperatorFlags/* /config/operatorflags
chown -R vrs:vrs /config/operatorflags
echo "Installing silhouettes..."
cp -R /opt/VRS_Extras/dedevillela/VRS-Silhouettes/Silhouettes/* /config/silhouettes/
chown -R vrs:vrs /config/silhouettes

